version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn test
  deploy:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn deploy
workflows:
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
